function jobs_scheduling(n, p, d1,d2,q1,q2, D)

C0 = 1;
C1 = 1;

 
figure
hold on
 for i = 1:n
    for j = 1:n
        if(Whittle_indices_limited_PS(i,p,q1, C0, C1, d1, D) > 0 && Whittle_indices_limited_PS(j,p,q2, C0, C1, d2, D)>0)
            if(Whittle_indices_limited_PS(i,p,q1, C0, C1, d1, D) > Whittle_indices_limited_PS(j,p,q2, C0, C1, d2, D))
                plot(i,j,'d',...
                'LineWidth',2,...
                'MarkerSize',6,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','w') 
            elseif(Whittle_indices_limited_PS(i,p,q1, C0, C1, d1, D) == Whittle_indices_limited_PS(j,p,q2, C0, C1, d2, D))
                plot(i,j,'--gs',...
                'LineWidth',2,...
                'MarkerSize',6,...
                'MarkerEdgeColor','b',...
                'MarkerFaceColor','w')    
            else
                plot(i,j,'*',...
                'LineWidth',2,...
                'MarkerSize',6,...
                'MarkerEdgeColor','r',...
                'MarkerFaceColor',[0,0,1])
            end    
                if(abs(Whittle_indices_limited_PS(i,p,q1, C0, C1, d1, D) - Whittle_indices_limited_PS(j,p,q2, C0, C1, d2, D))<=10^-2)
                  plot(i,j,'--gs',...
                 'LineWidth',2,...
                 'MarkerSize',6,...
                 'MarkerEdgeColor','b',...
                 'MarkerFaceColor','w')
                end
        elseif(Whittle_indices_limited_PS(i,p,q1, C0, C1, d1, D) > 0 && Whittle_indices_limited_PS(j,p,q2, C0, C1, d2, D)<0) 
             plot(i,j,'d',...
                'LineWidth',2,...
                'MarkerSize',6,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','w')
        
        elseif(Whittle_indices_limited_PS(i,p,q1, C0, C1, d1, D) < 0 && Whittle_indices_limited_PS(j,p,q2, C0, C1, d2, D) > 0) 
                 plot(i,j,'*',...
                'LineWidth',2,...
                'MarkerSize',6,...
                'MarkerEdgeColor','r',...
                'MarkerFaceColor',[0,0,1])
        else
            plot(i,j,'o',...
                'LineWidth',2,...
                'MarkerSize',6,...
                'MarkerEdgeColor','y',...
                'MarkerFaceColor',[0,0,1])
        end

    end
 end
 
 title('dispatching of jobs via index policy')
xlabel('Numbers in Queue 1')
ylabel('Numbers in Queue 2')
 annotation('textbox',...
     [0.780604133545311 0.310961968680089 0.197138314785373 0.505757751727713],...
     'String',{'Red: Q2','Black: Q1','blue: indifferent', 'yellow: blocking'},...
     'FitBoxToText','on',...
     'BackgroundColor',[1 1 1]);
 annotation('textbox',[0.5 0.3 0.1 0.5],'String',{'Arrival prob p:' p 'departure prob Q1' q1 'departure prob Q2' q2 'LPS-d1 for Q1' d1 'LPS-d2 for Q2' d2  'cost for rejection D' D ...
    },'BackgroundColor',[1 1 1],'FitBoxToText','on'  ); 
 
end 